export const mockCaseQueue = {
  cases: [
    {
      case_id: "uuid-1",
      case_number: "MH-2024-CR-10001",
      accused_name: "Rajesh Kumar",
      priority_score: 94.2,
      one_line_reason:
        "Eligible under S.479 — first offender, 40% of max served, hearing in 3 days",
      charges: [
        {
          section: "379",
          act: "IPC",
          description: "Theft",
          max_years: 3,
          life_or_death: false,
        },
      ],
      next_action: "File bail application before 14-Apr hearing",
      confidence: 0.87,
      bail_success_probability: 0.73,
      eligibility_status: "ELIGIBLE",
      countdown: { days: -47, display: "OVERDUE by 47 days", type: "overdue" as const },
      flags: ["OVERDUE", "TIME_SENSITIVE"],
      state: "Maharashtra",
      court: "Sessions Court, Pune",
      prison: "Yerwada Central Prison",
      detention_days: 412,
      next_hearing_date: "2026-04-14",
      arrest_date: "2025-02-23",
    },
    {
      case_id: "uuid-2",
      case_number: "UP-2025-CR-10042",
      accused_name: "Mohammed Iqbal",
      priority_score: 88.7,
      one_line_reason:
        "Becomes eligible in 5 days — hearing next week, lawyer assigned",
      charges: [
        {
          section: "420",
          act: "IPC",
          description: "Cheating",
          max_years: 7,
          life_or_death: false,
        },
      ],
      next_action: "Prepare bail application — eligibility window opening",
      confidence: 0.82,
      bail_success_probability: 0.61,
      eligibility_status: "PENDING",
      countdown: { days: 5, display: "Eligible in 5 days", type: "upcoming" as const },
      flags: ["TIME_SENSITIVE"],
      state: "Uttar Pradesh",
      court: "Magistrate Court, Lucknow",
      prison: "Lucknow District Prison",
      detention_days: 847,
      next_hearing_date: "2026-04-18",
      arrest_date: "2024-01-15",
    },
    {
      case_id: "uuid-3",
      case_number: "TN-2024-CR-10089",
      accused_name: "Suresh Rajan",
      priority_score: 72.1,
      one_line_reason:
        "Eligible but bail granted 45 days ago — surety ₹2,00,000 unexecuted (8× monthly income)",
      charges: [
        {
          section: "457",
          act: "IPC",
          description: "Lurking at Night",
          max_years: 5,
          life_or_death: false,
        },
      ],
      next_action: "Generate S.440 surety reduction brief",
      confidence: 0.91,
      bail_success_probability: null,
      eligibility_status: "ELIGIBLE",
      countdown: {
        days: -120,
        display: "OVERDUE by 120 days",
        type: "overdue" as const,
      },
      flags: ["OVERDUE", "SURETY_GAP"],
      state: "Tamil Nadu",
      court: "Sessions Court, Madurai",
      prison: "Madurai Central Prison",
      detention_days: 580,
      next_hearing_date: null,
      arrest_date: "2024-10-05",
    },
    {
      case_id: "uuid-4",
      case_number: "BR-2025-CR-10150",
      accused_name: "Arun Prasad",
      priority_score: 45.3,
      one_line_reason:
        "S.302 IPC — Murder charge — excluded from S.479 eligibility. Flagged for lawyer review.",
      charges: [
        {
          section: "302",
          act: "IPC",
          description: "Murder",
          max_years: 100,
          life_or_death: true,
        },
      ],
      next_action: "Lawyer review required — life imprisonment charge",
      confidence: 0.95,
      bail_success_probability: 0.12,
      eligibility_status: "EXCLUDED",
      countdown: { days: null, display: "N/A — excluded charge", type: "na" as const },
      flags: ["LAWYER_REVIEW"],
      state: "Bihar",
      court: "Sessions Court, Patna",
      prison: "Beur Central Prison",
      detention_days: 310,
      next_hearing_date: "2026-04-20",
      arrest_date: "2025-06-05",
    },
    {
      case_id: "uuid-5",
      case_number: "WB-2024-CR-10200",
      accused_name: "Kamal Halder",
      priority_score: 81.9,
      one_line_reason:
        "Eligible — hearing tomorrow but court has 87% adjournment rate. Consider Case MH-2024-CR-10001 first.",
      charges: [
        {
          section: "380",
          act: "IPC",
          description: "Theft in Dwelling",
          max_years: 7,
          life_or_death: false,
        },
      ],
      next_action: "Attend hearing — but high adjournment probability",
      confidence: 0.79,
      bail_success_probability: 0.55,
      eligibility_status: "ELIGIBLE",
      countdown: {
        days: -30,
        display: "OVERDUE by 30 days",
        type: "overdue" as const,
      },
      flags: ["OVERDUE", "HIGH_ADJOURNMENT"],
      state: "West Bengal",
      court: "District Court, Kolkata",
      prison: "Presidency Correctional Home",
      detention_days: 450,
      next_hearing_date: "2026-04-12",
      arrest_date: "2025-01-17",
    },
    {
      case_id: "uuid-6",
      case_number: "MH-2025-CR-10301",
      accused_name: "Vikram Patil",
      priority_score: 67.5,
      one_line_reason:
        "Approaching eligibility — first offender, S.498A IPC, detained 340 days of 365 threshold",
      charges: [
        {
          section: "498A",
          act: "IPC",
          description: "Cruelty by Husband/Relatives",
          max_years: 3,
          life_or_death: false,
        },
      ],
      next_action: "Prepare documentation for upcoming eligibility window",
      confidence: 0.84,
      bail_success_probability: 0.68,
      eligibility_status: "PENDING",
      countdown: {
        days: 25,
        display: "Eligible in 25 days",
        type: "upcoming" as const,
      },
      flags: ["TIME_SENSITIVE"],
      state: "Maharashtra",
      court: "Magistrate Court, Mumbai",
      prison: "Arthur Road Jail",
      detention_days: 340,
      next_hearing_date: "2026-05-02",
      arrest_date: "2025-05-06",
    },
    {
      case_id: "uuid-7",
      case_number: "UP-2024-CR-10402",
      accused_name: "Sanjay Verma",
      priority_score: 51.2,
      one_line_reason:
        "S.392 IPC Robbery — no lawyer assigned, moderate priority. Hearing in 3 weeks.",
      charges: [
        {
          section: "392",
          act: "IPC",
          description: "Robbery",
          max_years: 10,
          life_or_death: false,
        },
      ],
      next_action: "Assign panel lawyer — no legal representation",
      confidence: 0.76,
      bail_success_probability: 0.38,
      eligibility_status: "PENDING",
      countdown: {
        days: 180,
        display: "Eligible in 180 days",
        type: "upcoming" as const,
      },
      flags: ["NO_LAWYER"],
      state: "Uttar Pradesh",
      court: "Sessions Court, Varanasi",
      prison: "Varanasi District Prison",
      detention_days: 185,
      next_hearing_date: "2026-05-01",
      arrest_date: "2025-10-08",
    },
  ],
  total: 7,
};

export const mockReasoningGraph = {
  nodes: [
    {
      id: "fir",
      label: "FIR Text",
      value: "Hindi FIR — S.379 IPC referenced in paragraph 3",
      confidence: 1.0,
      type: "input" as const,
    },
    {
      id: "ocr",
      label: "OCR Processed",
      value: "Text extracted with 94% accuracy",
      confidence: 0.94,
      type: "process" as const,
    },
    {
      id: "charges",
      label: "Charges Extracted",
      value: "S.379 IPC — Theft",
      confidence: 0.92,
      type: "process" as const,
    },
    {
      id: "bnss",
      label: "BNSS Mapping",
      value: "S.379 IPC → S.303 BNS (equivalent)",
      confidence: 0.95,
      type: "data" as const,
    },
    {
      id: "sentence",
      label: "Max Sentence",
      value: "3 years (1095 days)",
      confidence: 0.98,
      type: "data" as const,
    },
    {
      id: "offender",
      label: "First Offender Check",
      value: "Yes — no prior convictions found",
      confidence: 0.88,
      type: "data" as const,
    },
    {
      id: "threshold",
      label: "Threshold (⅓)",
      value: "365 days (1 year)",
      confidence: 0.95,
      type: "compute" as const,
    },
    {
      id: "detention",
      label: "Current Detention",
      value: "412 days (1 year 47 days)",
      confidence: 1.0,
      type: "data" as const,
    },
    {
      id: "delay",
      label: "Accused Delays",
      value: "0 days excluded",
      confidence: 1.0,
      type: "data" as const,
    },
    {
      id: "multiple",
      label: "Multiple Cases Check",
      value: "No — only 1 pending case",
      confidence: 0.9,
      type: "data" as const,
    },
    {
      id: "result",
      label: "ELIGIBLE ✅",
      value: "Exceeded threshold by 47 days",
      confidence: 0.87,
      type: "result" as const,
    },
  ],
  edges: [
    { from: "fir", to: "ocr" },
    { from: "ocr", to: "charges" },
    { from: "charges", to: "bnss" },
    { from: "bnss", to: "sentence" },
    { from: "sentence", to: "threshold" },
    { from: "offender", to: "threshold" },
    { from: "threshold", to: "result" },
    { from: "detention", to: "result" },
    { from: "delay", to: "detention" },
    { from: "multiple", to: "result" },
  ],
};

export const mockPrisonHeatmap = {
  prisons: [
    { id: "p1", name: "Yerwada Central Prison", lat: 18.55, lng: 73.89, eligible_count: 142, total_count: 890, state: "Maharashtra", district: "Pune" },
    { id: "p2", name: "Arthur Road Jail", lat: 18.96, lng: 72.83, eligible_count: 210, total_count: 1200, state: "Maharashtra", district: "Mumbai" },
    { id: "p3", name: "Lucknow District Prison", lat: 26.85, lng: 80.95, eligible_count: 320, total_count: 1800, state: "Uttar Pradesh", district: "Lucknow" },
    { id: "p4", name: "Beur Central Prison", lat: 25.58, lng: 85.18, eligible_count: 280, total_count: 2100, state: "Bihar", district: "Patna" },
    { id: "p5", name: "Puzhal Central Prison", lat: 13.15, lng: 80.19, eligible_count: 95, total_count: 750, state: "Tamil Nadu", district: "Chennai" },
    { id: "p6", name: "Presidency Correctional Home", lat: 22.57, lng: 88.35, eligible_count: 180, total_count: 1100, state: "West Bengal", district: "Kolkata" },
    { id: "p7", name: "Varanasi District Prison", lat: 25.32, lng: 82.99, eligible_count: 195, total_count: 950, state: "Uttar Pradesh", district: "Varanasi" },
    { id: "p8", name: "Nagpur Central Prison", lat: 21.15, lng: 79.09, eligible_count: 165, total_count: 1050, state: "Maharashtra", district: "Nagpur" },
    { id: "p9", name: "Gaya Central Prison", lat: 24.80, lng: 85.01, eligible_count: 240, total_count: 1300, state: "Bihar", district: "Gaya" },
    { id: "p10", name: "Madurai Central Prison", lat: 9.93, lng: 78.12, eligible_count: 110, total_count: 680, state: "Tamil Nadu", district: "Madurai" },
  ],
};

export const mockAnalytics = {
  chargeDetention: [
    { charge: "S.302 Murder", avg_days: 890, count: 320 },
    { charge: "S.307 Attempt Murder", avg_days: 620, count: 410 },
    { charge: "S.376 Rape", avg_days: 540, count: 280 },
    { charge: "S.392 Robbery", avg_days: 380, count: 520 },
    { charge: "S.420 Cheating", avg_days: 290, count: 680 },
    { charge: "S.379 Theft", avg_days: 210, count: 890 },
    { charge: "S.498A Cruelty", avg_days: 180, count: 420 },
    { charge: "S.506 Intimidation", avg_days: 120, count: 310 },
  ],
  courtPerformance: [
    { court: "Sessions Court, Varanasi", avg_bail_days: 87, adj_rate: 0.89 },
    { court: "Magistrate Court, Patna", avg_bail_days: 72, adj_rate: 0.85 },
    { court: "District Court, Muzaffarpur", avg_bail_days: 65, adj_rate: 0.82 },
    { court: "Sessions Court, Lucknow", avg_bail_days: 45, adj_rate: 0.71 },
    { court: "Sessions Court, Pune", avg_bail_days: 28, adj_rate: 0.55 },
    { court: "Magistrate Court, Mumbai", avg_bail_days: 22, adj_rate: 0.48 },
  ],
  statusDistribution: [
    { name: "Eligible", value: 1240, color: "#10B981" },
    { name: "Pending", value: 2180, color: "#F59E0B" },
    { name: "Excluded", value: 890, color: "#EF4444" },
    { name: "Under Review", value: 690, color: "#8B5CF6" },
  ],
  systemAccuracy: [
    { week: "W1", eligibility: 78, adjournment: 65, bail: 62 },
    { week: "W2", eligibility: 81, adjournment: 68, bail: 64 },
    { week: "W3", eligibility: 83, adjournment: 71, bail: 67 },
    { week: "W4", eligibility: 85, adjournment: 74, bail: 69 },
    { week: "W5", eligibility: 87, adjournment: 76, bail: 72 },
    { week: "W6", eligibility: 88, adjournment: 78, bail: 74 },
    { week: "W7", eligibility: 89, adjournment: 79, bail: 76 },
    { week: "W8", eligibility: 91, adjournment: 81, bail: 78 },
  ],
  suretyIncome: [
    { district: "Muzaffarpur", surety: 200000, income: 9500, ratio: 21.1 },
    { district: "Gaya", surety: 150000, income: 8200, ratio: 18.3 },
    { district: "Varanasi", surety: 100000, income: 11000, ratio: 9.1 },
    { district: "Patna", surety: 250000, income: 15000, ratio: 16.7 },
    { district: "Lucknow", surety: 50000, income: 18000, ratio: 2.8 },
    { district: "Pune", surety: 75000, income: 22000, ratio: 3.4 },
    { district: "Mumbai", surety: 100000, income: 25000, ratio: 4.0 },
    { district: "Kolkata", surety: 80000, income: 14000, ratio: 5.7 },
    { district: "Madurai", surety: 60000, income: 12000, ratio: 5.0 },
    { district: "Chennai", surety: 120000, income: 20000, ratio: 6.0 },
  ],
};

export const mockHearings = [
  { id: "h1", case_number: "MH-2024-CR-10001", accused_name: "Rajesh Kumar", court: "Sessions Court, Pune", hearing_date: "2026-04-14", judge: "Hon. Justice P.K. Deshmukh", adjournment_prob: 0.42, charge_sheet_filed: true, status: "upcoming" },
  { id: "h2", case_number: "UP-2025-CR-10042", accused_name: "Mohammed Iqbal", court: "Magistrate Court, Lucknow", hearing_date: "2026-04-18", judge: "Hon. Justice R. Singh", adjournment_prob: 0.71, charge_sheet_filed: true, status: "upcoming" },
  { id: "h3", case_number: "WB-2024-CR-10200", accused_name: "Kamal Halder", court: "District Court, Kolkata", hearing_date: "2026-04-12", judge: "Hon. Justice S. Chatterjee", adjournment_prob: 0.87, charge_sheet_filed: false, status: "upcoming" },
  { id: "h4", case_number: "BR-2025-CR-10150", accused_name: "Arun Prasad", court: "Sessions Court, Patna", hearing_date: "2026-04-20", judge: "Hon. Justice A. Mishra", adjournment_prob: 0.55, charge_sheet_filed: true, status: "upcoming" },
  { id: "h5", case_number: "MH-2025-CR-10301", accused_name: "Vikram Patil", court: "Magistrate Court, Mumbai", hearing_date: "2026-05-02", judge: "Hon. Justice M. Kulkarni", adjournment_prob: 0.38, charge_sheet_filed: true, status: "upcoming" },
];

export const mockSuretyGaps = [
  { case_id: "uuid-3", case_number: "TN-2024-CR-10089", accused_name: "Suresh Rajan", surety_amount: 200000, monthly_income: 12000, income_ratio: 16.7, days_since_bail: 45, bail_date: "2026-02-25", court: "Sessions Court, Madurai", state: "Tamil Nadu", action: "S.440 surety reduction candidate" },
  { case_id: "uuid-s1", case_number: "UP-2024-CR-11234", accused_name: "Ramesh Yadav", surety_amount: 500000, monthly_income: 9500, income_ratio: 52.6, days_since_bail: 90, bail_date: "2026-01-10", court: "Sessions Court, Varanasi", state: "Uttar Pradesh", action: "URGENT: S.440 application needed" },
  { case_id: "uuid-s2", case_number: "BR-2025-CR-11567", accused_name: "Manish Kumar", surety_amount: 150000, monthly_income: 8200, income_ratio: 18.3, days_since_bail: 30, bail_date: "2026-03-11", court: "Magistrate Court, Gaya", state: "Bihar", action: "S.440 surety reduction candidate" },
  { case_id: "uuid-s3", case_number: "WB-2024-CR-11890", accused_name: "Biplab Das", surety_amount: 100000, monthly_income: 14000, income_ratio: 7.1, days_since_bail: 60, bail_date: "2026-02-10", court: "District Court, Howrah", state: "West Bengal", action: "Monitor — near affordability threshold" },
];

export const mockAuditLog = [
  { id: "a1", timestamp: "2026-04-11T09:15:00Z", case_id: "MH-2024-CR-10001", assessment_type: "eligibility", reasoning: "S.379 IPC, First offender, ⅓ threshold = 365 days, detained 412 days → ELIGIBLE", confidence: 0.87, paralegal_id: "Priya Sharma", paralegal_response: "acted_on", system_version: "1.0.0" },
  { id: "a2", timestamp: "2026-04-11T08:30:00Z", case_id: "UP-2025-CR-10042", assessment_type: "eligibility", reasoning: "S.420 IPC, First offender, ⅓ threshold = 852 days, detained 847 days → PENDING (5 days remaining)", confidence: 0.82, paralegal_id: "Priya Sharma", paralegal_response: "acted_on", system_version: "1.0.0" },
  { id: "a3", timestamp: "2026-04-11T08:00:00Z", case_id: "BR-2025-CR-10150", assessment_type: "eligibility", reasoning: "S.302 IPC — Life/Death imprisonment charge → EXCLUDED from S.479 eligibility", confidence: 0.95, paralegal_id: "Priya Sharma", paralegal_response: "flagged", system_version: "1.0.0" },
  { id: "a4", timestamp: "2026-04-10T16:00:00Z", case_id: "WB-2024-CR-10200", assessment_type: "priority", reasoning: "Priority recalculated: Eligible + Hearing tomorrow + High adjournment (87%) = 81.9", confidence: 0.79, paralegal_id: "Priya Sharma", paralegal_response: "acted_on", system_version: "1.0.0" },
  { id: "a5", timestamp: "2026-04-10T14:30:00Z", case_id: "TN-2024-CR-10089", assessment_type: "surety", reasoning: "Surety ₹2,00,000 vs income ₹12,000/month. Ratio: 16.7× — S.440 reduction candidate", confidence: 0.91, paralegal_id: null, paralegal_response: null, system_version: "1.0.0" },
];

export const mockFLNodes = [
  { id: "fl1", dlsa_code: "MH-PUNE", dlsa_name: "DLSA Pune", state: "Maharashtra", status: "ACTIVE", last_contribution: "2026-04-11T08:00:00Z", contribution_count: 42, data_quality_score: 0.92, accuracy_impact: +2.3, lat: 18.52, lng: 73.85 },
  { id: "fl2", dlsa_code: "UP-LKO", dlsa_name: "DLSA Lucknow", state: "Uttar Pradesh", status: "ACTIVE", last_contribution: "2026-04-11T06:00:00Z", contribution_count: 38, data_quality_score: 0.88, accuracy_impact: +1.8, lat: 26.85, lng: 80.95 },
  { id: "fl3", dlsa_code: "BR-PAT", dlsa_name: "DLSA Patna", state: "Bihar", status: "ACTIVE", last_contribution: "2026-04-10T22:00:00Z", contribution_count: 25, data_quality_score: 0.79, accuracy_impact: +1.2, lat: 25.61, lng: 85.14 },
  { id: "fl4", dlsa_code: "TN-CHE", dlsa_name: "DLSA Chennai", state: "Tamil Nadu", status: "INACTIVE", last_contribution: "2026-04-08T12:00:00Z", contribution_count: 15, data_quality_score: 0.71, accuracy_impact: +0.5, lat: 13.08, lng: 80.27 },
  { id: "fl5", dlsa_code: "WB-KOL", dlsa_name: "DLSA Kolkata", state: "West Bengal", status: "ACTIVE", last_contribution: "2026-04-11T07:30:00Z", contribution_count: 31, data_quality_score: 0.85, accuracy_impact: +1.5, lat: 22.57, lng: 88.36 },
];

export const mockWhatsAppMessages = [
  { id: "w1", sender: "system", text: "🙏 नमस्ते! JusticeGrid में आपका स्वागत है। कृपया अपना केस नंबर डालें।\n\nWelcome to JusticeGrid. Please enter your case number.", timestamp: "10:00 AM", language: "hi" },
];

export const mockSystemHealth = [
  { source: "eCourts Maharashtra", status: "healthy", last_updated: "2026-04-11T09:45:00Z", is_stale: false, latency_ms: 230 },
  { source: "eCourts Uttar Pradesh", status: "healthy", last_updated: "2026-04-11T09:30:00Z", is_stale: false, latency_ms: 450 },
  { source: "eCourts Bihar", status: "degraded", last_updated: "2026-04-11T06:00:00Z", is_stale: true, latency_ms: 1200 },
  { source: "eCourts Tamil Nadu", status: "healthy", last_updated: "2026-04-11T09:40:00Z", is_stale: false, latency_ms: 180 },
  { source: "eCourts West Bengal", status: "healthy", last_updated: "2026-04-11T09:15:00Z", is_stale: false, latency_ms: 320 },
  { source: "NJDG API", status: "healthy", last_updated: "2026-04-11T09:50:00Z", is_stale: false, latency_ms: 150 },
  { source: "Neon PostgreSQL", status: "healthy", last_updated: "2026-04-11T09:55:00Z", is_stale: false, latency_ms: 45 },
  { source: "Upstash Redis", status: "healthy", last_updated: "2026-04-11T09:55:00Z", is_stale: false, latency_ms: 12 },
  { source: "Gemini Flash API", status: "healthy", last_updated: "2026-04-11T09:50:00Z", is_stale: false, latency_ms: 890 },
  { source: "Bhashini API", status: "degraded", last_updated: "2026-04-10T18:00:00Z", is_stale: true, latency_ms: 3500 },
];
